language: c++

branches:
  only:
  - master

dist: trusty

# The PAL unit tests have a dependency on the PST timezone
env:
  - export TZ=':/usr/share/zoneinfo/America/Los_Angeles'

sudo: required

addons:
  apt:
    packages:
      - pkg-config
      - libpam0g-dev
      - librpm-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - rpm
      - time

before_install:
  - date

script:
  - cd build
  - ./configure
  - make all test
